version: "3"
services:
  mongoDB:
    container_name: "mongo_database"
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - .workdash.env
  node_server:
    container_name: "node_server"
    restart: "always"
    depends_on:
      - mongoDB
    build: .
    ports:
      - "5000:5000"
    links:
      - mongoDB
  adminMongo:
    image: "mrvautin/adminmongo"
    depends_on:
      - mongoDB
    ports:
      - "1234:1234"