version: "3"

services:

  mongo:
    image: "mongo_db"
    build: ./mongo_image
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db
    env_file:
      - ./mongo_image/.mongo_vars.env

  node_server:
    container_name: "node_server"
    restart: "always"
    depends_on:
      - mongo
    build: .
    ports:
      - "5000:5000"
      - "9229:9229"

  adminMongo:
    image: "mrvautin/adminmongo"
    depends_on:
      - mongo
    ports:
      - "1234:1234"